# Generated by Django 4.0.3 on 2022-04-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_service', '0003_remove_question_name_option_slug_alter_option_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Answer',
        ),
    ]
