# Generated by Django 4.0.3 on 2022-04-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_service', '0004_rename_option_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='slug',
        ),
    ]
