# Generated by Django 4.0.3 on 2022-04-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_service', '0005_remove_answer_slug_remove_question_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='Default question Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
